### ISSUE TITLE
Avoid flooding controller log with errors when a disk dies (index becomes unreadable)

### ISSUE THREAD

**Issue by gitj** [PolarMesosphericClouds/PMC-Turbo#18]
After a disk fails, the controller log fills with error messages as shown below because the watchers can no longer access their index files. This isn't a huge problem but is a nuisance when debugging.
<pre>
ERROR    2017-07-20 10:09:05,110 - pmc_turbo.utils.index_watcher.get_fragment:56  Failed to get fragment, something wrong with index file?
Traceback (most recent call last):
  File "/home/pmc/pmc-turbo/pmc_turbo/utils/index_watcher.py", line 37, in get_fragment
    modified = os.stat(self.filename).st_mtime
OSError: [Errno 2] No such file or directory: '/data4/2017-07-11_230910/index.csv'
ERROR    2017-07-20 10:09:05,111 - pmc_turbo.utils.index_watcher.get_fragment:56  Failed to get fragment, something wrong with index file?
Traceback (most recent call last):
  File "/home/pmc/pmc-turbo/pmc_turbo/utils/index_watcher.py", line 37, in get_fragment
    modified = os.stat(self.filename).st_mtime
</pre>

**Comment by gitj** [comment]
No easy way to solve this while still logging legitimate failures. Best course of action is to restart controller if a disk fails to clear stale indexes.
Closing for now
