### ISSUE TITLE
Avoid filling logs if controller fails

### ISSUE THREAD

**Issue by gitj** [PolarMesosphericClouds/PMC-Turbo#9]
If the controller goes offline, the communicator logs get filled with messages like below. The loop to get data has nothing else to do. Need to add some wait in case there is absolutely no controller.

log is on clouds:/data/pmc/pre-flight/2017-06-30-thermal-testing-logs/pmclogs/communicator.2017-07-07_152800.log
<pre>
DEBUG    2017-07-07 23:21:28,814 - pmc_turbo.communication.camera_communicator.send_data_on_downlinks:333  No data was obtained.
DEBUG    2017-07-07 23:21:28,825 - pmc_turbo.communication.camera_communicator.send_data_on_downlinks:310  Getting next data from camera 4
DEBUG    2017-07-07 23:21:28,825 - pmc_turbo.communication.camera_communicator.check_peer_connection:469  Pinging peer <Pyro4.core.Proxy at 0x7f923b263b90; connected; for PYRO:communicator@pmc-camera-4:40000>
DEBUG    2017-07-07 23:21:28,827 - pmc_turbo.communication.camera_communicator.get_next_data:368  Getting next data from controller.
DEBUG    2017-07-07 23:21:28,828 - pmc_turbo.communication.camera_communicator.get_next_data:374  Connection to controller failed. Error counter - controller_communication_errors : 1496883. Error message: Traceback (most recent call last):
  File "/home/pmc/pmc-turbo/pmc_turbo/communication/camera_communicator.py", line 369, in get_next_data
    return self.controller.get_next_data_for_downlink()
  File "/home/pmc/miniconda/envs/pmc/lib/python2.7/site-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/pmc/miniconda/envs/pmc/lib/python2.7/site-packages/Pyro4/core.py", line 417, in _pyroInvoke
    self.__pyroCreateConnection()
  File "/home/pmc/miniconda/envs/pmc/lib/python2.7/site-packages/Pyro4/core.py", line 527, in __pyroCreateConnection
    raise ce
CommunicationError: cannot connect to ('0.0.0.0', 50001): [Errno 111] Connection refused

DEBUG    2017-07-07 23:21:28,829 - pmc_turbo.communication.camera_communicator.send_data_on_downlinks:333  No data was obtained.
DEBUG    2017-07-07 23:21:28,839 - pmc_turbo.communication.camera_communicator.send_data_on_downlinks:310  Getting next data from camera 4
DEBUG    2017-07-07 23:21:28,840 - pmc_turbo.communication.camera_communicator.check_peer_connection:469  Pinging peer <Pyro4.core.Proxy at 0x7f923b263b90; connected; for PYRO:communicator@pmc-camera-4:40000>
DEBUG    2017-07-07 23:21:28,841 - pmc_turbo.communication.camera_communicator.get_next_data:368  Getting next data from controller.
DEBUG    2017-07-07 23:21:28,842 - pmc_turbo.communication.camera_communicator.get_next_data:374  Connection to controller failed. Error counter - controller_communication_errors : 1496884. Error message: Traceback (most recent call last):
  File "/home/pmc/pmc-turbo/pmc_turbo/communication/camera_communicator.py", line 369, in get_next_data
    return self.controller.get_next_data_for_downlink()
  File "/home/pmc/miniconda/envs/pmc/lib/python2.7/site-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/pmc/miniconda/envs/pmc/lib/python2.7/site-packages/Pyro4/core.py", line 417, in _pyroInvoke
    self.__pyroCreateConnection()
  File "/home/pmc/miniconda/envs/pmc/lib/python2.7/site-packages/Pyro4/core.py", line 527, in __pyroCreateConnection
    raise ce
CommunicationError: cannot connect to ('0.0.0.0', 50001): [Errno 111] Connection refused
</pre>

**Comment by gitj** [comment]
As a workaround, 10aaed8dae73c566ce6f8154d53c7cb3a56d28d5 limits log files to 1 GB for each application, to avoid recklessly filling up the disk.
Still working on a reasonable fix to the root problem that doesn't throttle communication when multiple cameras are present
